#page title
page_title                                : Simple Food Log                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6544782852                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Simple Food Log                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your food journal made simple.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Lee Martin
your_link                                 :
your_city                                 : Birmingham, Alabama
email_address                             : lee.b.martin@gmail.com
linkedin_username                         :
linkedin_company                          :
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Privacy First
    description                           : All your data stays on your device. No cloud storage, no tracking, complete control over your information.
    fontawesome_icon_name                 : lock

  - title                                 : Photo Logging
    description                           : Capture meals with your camera or choose from your photo library. Visual tracking made effortless.
    fontawesome_icon_name                 : camera

  - title                                 : Detailed Notes
    description                           : Add context to every meal with detailed notes. Track what you ate, how you felt, and more.
    fontawesome_icon_name                 : edit

  - title                                 : Professional Reports
    description                           : Generate beautifully formatted PDF reports to share with your dietitian or healthcare provider.
    fontawesome_icon_name                 : file-pdf

  - title                                 : Easy Sharing
    description                           : Share your food logs via email or save PDFs directly to your device with one tap.
    fontawesome_icon_name                 : share-alt

  - title                                 : Complete History
    description                           : Browse your entire food log history with date filtering. Never lose track of your journey.
    fontawesome_icon_name                 : calendar-alt

  - title                                 : Simple Interface
    description                           : Clean, intuitive design with no complicated setup. Start logging your meals in seconds.
    fontawesome_icon_name                 : star

  - title                                 : Dietitian Contacts
    description                           : Store your dietitian's contact information for quick and easy communication.
    fontawesome_icon_name                 : user-md



# Theme Settings
topbar_color                              : "#FFDFCC"
topbar_transparency                       : 0.9
topbar_title_color                        : "#000000"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#FFDFCC"
cover_overlay_transparency                : 0.7

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FF9999"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#333333"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FF9999"
feature_icons_background_color            : "#FFDFCC"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#FFDFCC"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
